FROM rust:latestFROM greyltc/archlinux-aur:yay

RUN yay -Suuy

RUN sudo -u ab -D~ bash -c 'yay -Syu --removemake --needed --noprogressbar --noconfirm gnome-shell-extension-forge'
RUN sudo -u ab -D~ bash -c 'yay -Syu --removemake --needed --noprogressbar --noconfirm gnome-shell-extension-vitals'
