FROM greyltc/archlinux-aur:yay

RUN sudo -u ab -D~ bash -c 'yay -Suuy --removemake --needed --noprogressbar --noconfirm'

RUN sudo -u ab -D~ bash -c 'yay -Syu --removemake --needed --noprogressbar --noconfirm gnome-shell-extension-forge'
RUN sudo -u ab -D~ bash -c 'yay -Syu --removemake --needed --noprogressbar --noconfirm gnome-shell-extension-vitals'
