ARG FEDORA_VERSION="${FEDORA_VERSION:-38}"
FROM fedora:${FEDORA_VERSION}
RUN dnf -y update
RUN dnf install -y git cmake pkgconf-pkg-config
RUN dnf group install -y "C Development Tools and Libraries" "Development Tools"
WORKDIR /tmp
RUN git clone -b master https://github.com/fastfetch-cli/fastfetch.git && \
    cd fastfetch && \
    mkdir -p build && \
    cd build && \
    cmake .. && \
    cmake --build . --target fastfetch --target flashfetch
